Algoritmo "o raio de um círculo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2024
Var
// Seção de Declarações das variáveis 
  n, x: real

Inicio
  escreval(" Digite um número: ")
  leia(n)
  x <- (3.14* n*n)
  escreval("O raio do círclo é: ", x)



Fimalgoritmo